#springboot-sti-exstream
FROM springboot-sti

LABEL io.k8s.description="Platform for building Spring Boot applications packaged with exstream" \
      io.k8s.display-name="Spring Boot Exstream builder 1.0" \
      io.openshift.expose-services="8080:http" \
      io.openshift.tags="builder,maven-3,gradle-2.6,springboot"